-- MySQL Script generated by MySQL Workbench
-- Thu Aug 15 18:52:57 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema lddc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lddc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lddc` DEFAULT CHARACTER SET utf8 ;
USE `lddc` ;

-- -----------------------------------------------------
-- Table `lddc`.`Localisation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lddc`.`Localisation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `world` VARCHAR(45) NULL,
  `coordinates` JSON NULL,
  `description` VARCHAR(45) NULL,
  `places` JSON NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lddc`.`ChronologyCharacter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lddc`.`ChronologyCharacter` (
  `idCharacter` INT NOT NULL AUTO_INCREMENT,
  `background` VARCHAR(45) NULL,
  `picture` VARCHAR(45) NULL,
  `race` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL,
  `idLocalisation` INT NOT NULL,
  PRIMARY KEY (`idCharacter`, `idLocalisation`),
  INDEX `fk_ChronologyCharacter_Localisation_idx` (`idLocalisation` ASC) VISIBLE,
  CONSTRAINT `fk_ChronologyCharacter_Localisation`
    FOREIGN KEY (`idLocalisation`)
    REFERENCES `lddc`.`Localisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lddc`.`Chronology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lddc`.`Chronology` (
  `idChronology` INT NOT NULL AUTO_INCREMENT,
  `events` JSON NULL,
  `idLocalisation` INT NOT NULL,
  PRIMARY KEY (`idChronology`, `idLocalisation`),
  INDEX `fk_Chronology_Localisation1_idx` (`idLocalisation` ASC) VISIBLE,
  CONSTRAINT `fk_Chronology_Localisation1`
    FOREIGN KEY (`idLocalisation`)
    REFERENCES `lddc`.`Localisation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lddc`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lddc`.`User` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `role` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;